{"name": "用户注册登录查看-预期成功", "status": "failed", "statusDetails": {"message": "AssertionError: assert '查询用户信息成功' in 'success'\n +  where 'success' = <core.result_base.ResultBase object at 0x106dc3a30>.msg", "trace": "self = <testcases.scenario_test.test_kuai_register_login_list.TestRegLogList object at 0x106d019d0>\ntestcase_data_kuai = {'except_code': 200, 'except_msg': '查询用户信息成功', 'except_result': True, 'login': {'phone': '13800138000', 'username': '小花平台', 'verificationCode': '123456'}}\n\n    @allure.story(\"用例--注册/登录/查看--预期成功\")\n    @allure.description(\"该用例是针对 注册-登录-查看 场景的测试\")\n    @allure.issue(\"https://www.cnblogs.com/wintest\", name=\"点击，跳转到对应BUG的链接地址\")\n    @allure.testcase(\"https://www.cnblogs.com/wintest\", name=\"点击，跳转到对应用例的链接地址\")\n    @allure.title(\"用户注册登录查看-预期成功\")\n    @pytest.mark.multiple\n    # @pytest.mark.usefixtures(\"delete_register_user\")#如果一个方法或者一个class用例想要同时调用多个fixture，可以使用@pytest.mark.usefixture()进行叠加。注意叠加顺序，先执行的放底层，后执行的放上层。\n    def test_user_register_login_update_success(self, testcase_data_kuai):\n        username = testcase_data_kuai[\"login\"][\"username\"]\n        verificationCode = testcase_data_kuai[\"login\"][\"verificationCode\"]\n        phone = testcase_data_kuai[\"login\"][\"phone\"]\n    \n        except_result = testcase_data_kuai[\"except_result\"]\n        except_code = testcase_data_kuai[\"except_code\"]\n        except_msg = testcase_data_kuai[\"except_msg\"]\n    \n        logger.info(\"*************** 开始执行用例 ***************\")\n        result = login_user(phone, verificationCode)\n        step_2(phone)\n        token = result.token\n        logger.info(\"-------------{}\".format(token))\n        assert result.success is True, result.error\n    \n        result = get_one_user_info(token)\n        step_3(username)\n    \n        assert result.success == except_result, result.error\n        logger.info(\"code ==>> 期望结果：{}， 实际结果：【 {} 】\".format(except_code, result.response.json().get(\"code\")))\n        assert result.response.json().get(\"code\") == except_code\n>       assert except_msg in result.msg\nE       AssertionError: assert '查询用户信息成功' in 'success'\nE        +  where 'success' = <core.result_base.ResultBase object at 0x106dc3a30>.msg\n\ntest_kuai_register_login_list.py:57: AssertionError"}, "description": "该用例是针对 注册-登录-查看 场景的测试", "steps": [{"name": "步骤2 ==>> 登录用户", "status": "passed", "parameters": [{"name": "phone", "value": "'13800138000'"}], "start": 1628153848517, "stop": 1628153848517}, {"name": "步骤3 ==>> 获取某个用户信息", "status": "passed", "parameters": [{"name": "username", "value": "'小花平台'"}], "start": 1628153848614, "stop": 1628153848614}], "attachments": [{"name": "log", "source": "344641de-834b-44b9-829c-b7c562c12b90-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "c4a7c671-5c68-483f-87c1-bf013742206b-attachment.txt", "type": "text/plain"}], "start": 1628153848440, "stop": 1628153848614, "uuid": "dcc02d9c-1c05-4072-8f70-c28e1706c04b", "historyId": "2f9e2033e857a196e3cfafbf0e3c91fb", "testCaseId": "c78b7fc66a86a49af4c08176ea915368", "fullName": "testcases.scenario_test.test_kuai_register_login_list.TestRegLogList#test_user_register_login_update_success", "labels": [{"name": "epic", "value": "针对业务场景的测试"}, {"name": "severity", "value": "critical"}, {"name": "feature", "value": "场景：用户注册-用户登录-查看用户"}, {"name": "story", "value": "用例--注册/登录/查看--预期成功"}, {"name": "tag", "value": "multiple"}, {"name": "parentSuite", "value": "testcases.scenario_test"}, {"name": "suite", "value": "test_kuai_register_login_list"}, {"name": "subSuite", "value": "TestRegLogList"}, {"name": "host", "value": "zengxiaohua.local"}, {"name": "thread", "value": "11258-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.scenario_test.test_kuai_register_login_list"}], "links": [{"type": "test_case", "url": "https://www.cnblogs.com/wintest", "name": "点击，跳转到对应用例的链接地址"}, {"type": "issue", "url": "https://www.cnblogs.com/wintest", "name": "点击，跳转到对应BUG的链接地址"}]}