{"name": "测试数据：【 13800138000，111111，True，0，success】", "status": "failed", "statusDetails": {"message": "AssertionError: 接口返回码是 【 1001 】, 返回信息：请求参数不合法 \nassert False == True", "trace": "self = <testcases.api_test.test_kuai_login.TestUserLogin object at 0x10cd97220>\nphone = '13800138000', verificationCode = '111111', except_result = True\nexcept_code = 0, except_msg = 'success'\n\n    @allure.story(\"用例--登录用户\")\n    @allure.description(\"该用例是针对获取用户登录接口的测试\")\n    @allure.issue(\"https://www.cnblogs.com/wintest\", name=\"点击，跳转到对应BUG的链接地址\")\n    @allure.testcase(\"https://www.cnblogs.com/wintest\", name=\"点击，跳转到对应用例的链接地址\")\n    @allure.title(\"测试数据：【 {phone}，{verificationCode}，{except_result}，{except_code}，{except_msg}】\")\n    @pytest.mark.single\n    @pytest.mark.parametrize(\"phone, verificationCode, except_result, except_code, except_msg\",\n                             api_kuai_data[\"test_login_user\"])\n    def test_login_user(self, phone, verificationCode, except_result, except_code, except_msg):\n        logger.info(\"*************** 开始执行用例 ***************\")\n        result = login_user(phone, verificationCode)\n        print(\"result:\",result)\n        step_1(phone)\n>       assert result.success == except_result, result.error\nE       AssertionError: 接口返回码是 【 1001 】, 返回信息：请求参数不合法 \nE       assert False == True\n\ntest_kuai_login.py:31: AssertionError"}, "description": "该用例是针对获取用户登录接口的测试", "steps": [{"name": "步骤1 ==>> 登录用户", "status": "passed", "parameters": [{"name": "phone", "value": "'13800138000'"}], "start": 1628071033862, "stop": 1628071033862}], "attachments": [{"name": "log", "source": "878ecdf2-3934-4064-9b38-366af3b5abfe-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "30d7b053-bb42-4559-80bf-a9f885888a7e-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "f109d4e3-5eac-4242-975c-13b76c74f65b-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "phone", "value": "'13800138000'"}, {"name": "verificationCode", "value": "'111111'"}, {"name": "except_result", "value": "True"}, {"name": "except_code", "value": "0"}, {"name": "except_msg", "value": "'success'"}], "start": 1628071033818, "stop": 1628071033863, "uuid": "de4db923-d952-4c46-a5ad-a33bb708b75e", "historyId": "d6233ac4c765a841f06f7de4dfad4f4e", "testCaseId": "4cf2c2f7c5a680a41fe59cb327f3c0a1", "fullName": "testcases.api_test.test_kuai_login.TestUserLogin#test_login_user", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "用户登录模块"}, {"name": "epic", "value": "针对单个接口的测试"}, {"name": "story", "value": "用例--登录用户"}, {"name": "tag", "value": "single"}, {"name": "parentSuite", "value": "testcases.api_test"}, {"name": "suite", "value": "test_kuai_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "zengxiaohua.local"}, {"name": "thread", "value": "2243-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.api_test.test_kuai_login"}], "links": [{"type": "test_case", "url": "https://www.cnblogs.com/wintest", "name": "点击，跳转到对应用例的链接地址"}, {"type": "issue", "url": "https://www.cnblogs.com/wintest", "name": "点击，跳转到对应BUG的链接地址"}]}