{"name": "test_login_user[\\u6d4b\\u8bd5test-123456-False-1003-\\u7528\\u6237\\u540d\\u4e0d\\u5b58\\u5728]", "status": "broken", "statusDetails": {"message": "KeyError: 'password'", "trace": "self = <allure_pytest.listener.AllureListener object at 0x1066b0fd0>\nitem = <Function test_login_user[\\u6d4b\\u8bd5test-123456-False-1003-\\u7528\\u6237\\u540d\\u4e0d\\u5b58\\u5728]>\n\n    @pytest.hookimpl(hookwrapper=True)\n    def pytest_runtest_setup(self, item):\n        if not self._cache.get(item.nodeid):\n            uuid = self._cache.push(item.nodeid)\n            test_result = TestResult(name=item.name, uuid=uuid, start=now(), stop=now())\n            self.allure_logger.schedule_test(uuid, test_result)\n    \n        yield\n    \n        uuid = self._cache.get(item.nodeid)\n        test_result = self.allure_logger.get_test(uuid)\n        for fixturedef in _test_fixtures(item):\n            group_uuid = self._cache.get(fixturedef)\n            if not group_uuid:\n                group_uuid = self._cache.push(fixturedef)\n                group = TestResultContainer(uuid=group_uuid)\n                self.allure_logger.start_group(group_uuid, group)\n            self.allure_logger.update_group(group_uuid, children=uuid)\n        params = item.callspec.params if hasattr(item, 'callspec') else {}\n    \n>       test_result.name = allure_name(item, params)\n\n../../../../djangoprj/venv/lib/python3.8/site-packages/allure_pytest/listener.py:88: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nitem = <Function test_login_user[\\u6d4b\\u8bd5test-123456-False-1003-\\u7528\\u6237\\u540d\\u4e0d\\u5b58\\u5728]>\nparameters = {'except_code': 1003, 'except_msg': '用户名不存在', 'except_result': False, 'username': '测试test', ...}\n\n    def allure_name(item, parameters):\n        name = escape_name(item.name)\n        title = allure_title(item)\n>       return title.format(**parameters) if title else name\nE       KeyError: 'password'\n\n../../../../djangoprj/venv/lib/python3.8/site-packages/allure_pytest/utils.py:112: KeyError"}, "start": 1628069418322, "stop": 1628069418322, "uuid": "8860f73e-6e7f-4eb1-ba2f-6b7cdf6b114c", "labels": [{"name": "severity", "value": "normal"}, {"name": "story", "value": "用例--登录用户"}, {"name": "feature", "value": "用户登录模块"}, {"name": "epic", "value": "针对单个接口的测试"}, {"name": "tag", "value": "single"}, {"name": "parentSuite", "value": "testcases.api_test"}, {"name": "suite", "value": "test_kuai_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "zengxiaohua.local"}, {"name": "thread", "value": "1955-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.api_test.test_kuai_login"}], "links": [{"type": "test_case", "url": "https://www.cnblogs.com/wintest", "name": "点击，跳转到对应用例的链接地址"}, {"type": "issue", "url": "https://www.cnblogs.com/wintest", "name": "点击，跳转到对应BUG的链接地址"}]}